### ISSUE TITLE
Implement validation for each test case.

### ISSUE THREAD

**Issue by thewillyhuman** [weso/hercules-ontology#111]
Once we defined each test case a the set of paths to the corresponding files for each needed element we can continue by calling the validation process. This validation process is intended to use @labra shex validation library.

The library requires 3 arguments, the graph, the schema and the shape map. In this case we have 5, and the way to match them is the following.
- **graph:** ontology + data
- **schema:** schema
- **shape map:** input shape map

And the result that returns this validation process is another shape map that is the one that must be equal to the `expectedShapeMapFile`.

**Comment by thewillyhuman** [comment]
Hey @mistermboy can u try to implement this?

**Comment by mistermboy** [comment]
Okay

**Comment by thewillyhuman** [comment]
Closed at #102
