### ISSUE TITLE
CQ006 - Obtain a list of scientific production in a range of time with important metadata. 

### ISSUE THREAD

**Issue by sofimrtn** [weso/hercules-ontology#17]
Original source:

> Como usuario requiero obtener un listado de la producción científica en un determinado rango de fechas de un centro/estructura de investigación en un área/disciplina. Para cada resultado se incluirán algunos metadatos importantes de la producción como, por ejemplo, DOI, año de publicación, etc.

Translated: 

> As a user I would like to obtain a list of the scientific production in a specific range of time from a research center/structure in a specific area/discipline. For each result, importan production metadata will be included, such as year of publication, DOI, etc.

**Comment by spitxa** [comment]
as i'm moving property _asio:hasDOI_ as subproperty of _asio:identifier_, the query will have to be slightly modified.
