### ISSUE TITLE
Add proposals representation to Github Pages

### ISSUE THREAD

**Issue by alejgh** [weso/hercules-ontology#2]
As of now we have a [proposals folder](https://github.com/weso/hercules-ontology/tree/master/proposals) with proposals for new items and properties that could be added to the ontology.

We should add an html file and deploy it to Github Pages to view and manage those proposals in an easier and more efficient way, similar to what was done with [shex-lite-evolution](http://weso.github.io/shex-lite-evolution).

**Comment by thewillyhuman** [comment]
Is it fixed with http://www.weso.es/hercules-ontology/ ?

**Comment by alejgh** [comment]
Yes, this issue was fixed in #4, I forgot to link the pull request to it.

We can close it now.
