### ISSUE TITLE
CQ012 - Participation percentage of a research center/structure. 

### ISSUE THREAD

**Issue by sofimrtn** [weso/hercules-ontology#20]
Original source:

> Como usuario necesito conocer el porcentaje de participación de un centro/estructura de investigación en proyectos nacionales o europeos.

Translated:

> As a user I would need to know the participation percentage of a certain research center/structure in european and national projects.

**Comment by alejgh** [comment]
I think this can be done at the moment for European projects, but not for national ones. I have seen http://www.asio.es/asioontologies/asio#EuropeanProject in the ontology, but I don't know how if there is a way to model the national projects. @spitxa

**Comment by alejgh** [comment]
We have ready the 'participant' property to link research institutes and projects.
