### ISSUE TITLE
CQ016 - Comparative visualizations of researchers' evolution. 

### ISSUE THREAD

**Issue by sofimrtn** [weso/hercules-ontology#23]
Original source:

> Como usuario necesito una visualización que me permita analizar la evolución de un investigador, conjunto de investigadores o líneas de investigación a través de los resultados de los proyectos realizados. Se podrá hacer una selección de los proyectos a incluir. El usuario podrá acceder a visualizaciones comparativas de la información de investigadores, conjuntos de investigadores o líneas de investigación seleccionados.

Translated:

> As a user I would need a visualization which allows me to analyze the evolution of a certain researcher, group of researchers or lines of research based on the results of developed projects. A selection of the projects may be made. The user may access the comparative visualizations between the different selected groups.

**Comment by spitxa** [comment]
a property _asio:projectOutcome_ would be interesting to be taken into account, as it could link a given project to publications, patents, prototypes, products, etc.

**Comment by spitxa** [comment]
property _asio:projectOutcome_ created with the domain _foaf:Project_ and the range open. as i included in the corresponding rdfs:comment the range can include publications, patents, products, prototypes, etc.
