### ISSUE TITLE
CQ024 - Profile and evolution of relationships between companies and research groups.

### ISSUE THREAD

**Issue by sofimrtn** [weso/hercules-ontology#27]
Original source:

> Como decisor tengo interés en conocer el perfil y evolución de la relación de investigación y transferencia de una empresa con un conjunto de centros de investigación en un período de tiempo.

Translated:

> As a "decisor" I am interested in knowing the profile and evolution of the research relationship and transfer between a specific company and a group of research centers at a specific time.

**Comment by spitxa** [comment]
property _asio:participant_ should be enough to link companies and universities around a project.
