### ISSUE TITLE
CQ026 - List of conferences/workshops and scientific outreach events. 

### ISSUE THREAD

**Issue by sofimrtn** [weso/hercules-ontology#28]
Original source:

> Obtener el listado de congresos/workshops y eventos de divulgación científica en los que haya participado indicando el rol que he tenido: organizador, expositor, etc.

Translated:

> Obtain a list of conferences/workshops and scientific outreach events in which I have participated, indicating the role: organizer, speaker, etc.

**Comment by spitxa** [comment]
created classes _Conference_ and _Workshop_ as subclasses of _Event_; created new role _EventOrganiser_.

**Comment by spitxa** [comment]
added a couple of conferences and a workshop linked to researcher labra using property _asio:participant_.
