### ISSUE TITLE
CQ032 - Trajectory based on a parametrizable timeline and criteria. 

### ISSUE THREAD

**Issue by sofimrtn** [weso/hercules-ontology#33]
Original source:

> Visualizar mi trayectoria según la línea del tiempo y parametrizable de acuerdo criterios como, por ejemplo, proyectos, tesis dirigidas/codirigidas, etc.

Translated:

> Take a look at my trajectory according to a parametrizable timeline and criteria such as projects, directed/codirected thesis..

**Comment by spitxa** [comment]
property _asio:supervised_ should be complement with another one: _asio:co-supervised_ to deal with the codirectors
