### ISSUE TITLE
CQ036 - University ranking based on funding. 

### ISSUE THREAD

**Issue by sofimrtn** [weso/hercules-ontology#38]
Original source:

> Estadísticas: ¿Puedo hacer un ranking de universidades que más fondos han obtenido por temática a nivel nacional o regional?

Translated:

> Statistics: ¿Can I make a university ranking based on which one has obtained more funding by topic in a regional or national level?

**Comment by alejgh** [comment]
We already have enough information in the ontology to start working on this issue.

We need to create a SPARQL query and add instances to our wikibase instance to show how this competence question is answered.

I will add this as a task for the next week.

**Comment by alejgh** [comment]
We need to move this issue to another week since there is still not a clear way to link the Universities with the projects.
