### ISSUE TITLE
CQ027 - Obtain the list of patents registered as a titular

### ISSUE THREAD

**Issue by alejgh** [weso/hercules-ontology#41]
Original source:
> Obtener el listado de patentes, diseños industriales, etc. que haya registrado como
titular o cotitular X o Y persona, Z o K institución.
<br>

Translated:
> Obtain the list of patents, industrial designs, etc. that I have registered as an owner or co-owner (person or institution).

**Comment by spitxa** [comment]
as i'm moving the _asio:Patent_ as subclass of _foaf:Document_, the query will have to be slightly modified.
