### ISSUE TITLE
CQ040 - Andalusian Universities publications ft. non-european researchers in relevant academic magazines. 

### ISSUE THREAD

**Issue by sofimrtn** [weso/hercules-ontology#42]
Original source:

> Estadísticas: Publicaciones de Universidades andaluzas en colaboración con investigadores fuera de la UE en revistas académicas de impacto.

Translated:

> Statistics: Andalusian Universities' publications featuring researchers from out of the European Union in relevant academic magazines.

**Comment by spitxa** [comment]
already available:
-the geopolitical module including both the 1st level (andalucia) and the 2nd  (provinces of andalucia)
-property "core#geoDivision"

missing:
-dataset of universities (but i'm already working in a sample one containing at least some instances)

**Comment by alejgh** [comment]
Nice, this is the last CQ we will be doing this week. Hope we can have the sample before then.

**Comment by alejgh** [comment]
We have to move this issue to another week, since we still need to find a way to represent the non-europeans researchers.

**Comment by spitxa** [comment]
property _asio:country_ can be used to link _foaf:Person_ to the class _asio:Country_ (country or other political subdivisions too). this property has not domain so any resource unpredicted could benefit from it (university, product, etc.)

<img width="1023" alt="Captura de Pantalla 2020-04-29 a les 10 08 31" src="https://user-images.githubusercontent.com/28587554/80574474-314e3c80-8a02-11ea-8141-e6a57ceaa817.png">

**Comment by spitxa** [comment]
other things needed:
-full list of countries
-ad hoc concept schemes to represent transnational institutions (EU, Schengen, CE, etc.)

**Comment by spitxa** [comment]
added:
-full list of countries
-ad hoc concept schemes to represent transnational institutions (EU, Schengen, CE, etc.)
-added publication, researcher and _asio:coauthores_ property
