### ISSUE TITLE
CQ042: Grants of a center in a scientific domain

### ISSUE THREAD

**Issue by sofimrtn** [weso/hercules-ontology#44]
Original source:

> Puedo ver quien tiene ERCs, Marie Curie, etc. ¿De mi centro y otros centros en una temática concreta?

Translated:

> Can I see who has ERCs, Marie Curie, etc from my own research center and others in a specific topic?

**Comment by spitxa** [comment]
a pivotal class _asio:Grant_ should be added to the core.

**Comment by spitxa** [comment]
added _asio:Grant_ as subclass of _asio:Funding_; including rdfs:comment & labels in english
