### ISSUE TITLE
CQ046 - Project results by specific topic of projects developed in the network. 

### ISSUE THREAD

**Issue by sofimrtn** [weso/hercules-ontology#47]
Original source:

> Estado del arte: ¿puedo ver los resultados de proyectos por temática concreta de proyectos desarrollados en la red, diferenciando a nivel regional, nacional, europeo?

Translated:

> Can I see project results by specific topic of projects developed in the network, making a distinction between national, regional and european levels?

**Comment by alejgh** [comment]
We need to represent the project outcome in the ontology, as stated in #23

**Comment by spitxa** [comment]
property _asio:projectOutcome_ created with the domain _foaf:Project_ and the range open. as i included in the corresponding rdfs:comment the range can include publications, patents, products, prototypes, etc.
