### ISSUE TITLE
CQ043 - Identify universities with excellence distinctions

### ISSUE THREAD

**Issue by alejgh** [weso/hercules-ontology#53]
Original source:
> ¿Puedo identificar qué universidades de la red cuentan con la distinción de excelencia Severo Ochoa, María de Maeztu o las equivalentes a nivel regional y por temática?
<br>

Translated:
> Am I able to identify which universities from the network have the Severo Ochoa, María de Maeztu or equivalent excellence distinctions at the regional level and grouped by theme?

**Comment by spitxa** [comment]
we should be capable of linking a research institute with its _mother ship_, when applicable.
