### ISSUE TITLE
Automate ontology publishing process

### ISSUE THREAD

**Issue by thewillyhuman** [weso/hercules-ontology#64]
Automate the ontology publication process to convert to RDF and visualize with some tool that we had looked at or with something similar to what they use in SWEET so that the URIs are referenceable.

**Comment by alejgh** [comment]
Some references:

[Sweet ontology wiki](https://github.com/ESIPFed/sweet/wiki/sweetontology.net)
[Ontoology tool](https://ontoology.linkeddata.es)
[LODE](https://essepuntato.it/lode/)
