### ISSUE TITLE
prune/improve alignments

### ISSUE THREAD

**Issue by spitxa** [weso/hercules-ontology#66]
as highlighted by a reviewer, the current list of alignments needs to be pruned. several among the aligned ontologies are not versioned and should be removed from the mappings or 'seized' (in case the are not maintained anymore). other mappings point to a heterogeneous classes not necessarily consistent between each other (i.e. class 'organization'). some are even not dereferenciable.

**Comment by thewillyhuman** [comment]
Any update here @spitxa ? 🤓

**Comment by spitxa** [comment]
pruned alignments & committed
