### ISSUE TITLE
Add default implementation for the ontology processor

### ISSUE THREAD

**Issue by thewillyhuman** [weso/hercules-ontology#74]
@othub Can you please add a default implementation to the ontology processor? The trait to be implemented is:

https://github.com/weso/hercules-ontology/blob/d811d7824a1c7d0d5213dda172aee49343673a9c/ci/src/main/scala/es/weso/asio/ci/OntologyProcessor.scala#L1-L23

If yes please fork, create a branch for the feature and from that branch initiate a PR to this [branch](https://github.com/weso/hercules-ontology/tree/ci-dev).

**Comment by othub** [comment]
@thewilly should i implement this trait in a new class or should i use the already existent IO ?
