### ISSUE TITLE
🚩 Red de ontologías hércules

### ISSUE THREAD

**Issue by thewillyhuman** [weso/hercules-ontology#85]
El día 15 de mayo de 2020 se realiza la entrega del hito 1 para el proyecto hércules. Este issue representa el entregable **_Red de Ontologías Hércules_** del cual el tipo de entregable es: **_Ontologías_**.

**Comment by thewillyhuman** [comment]
@spitxa podrías dar una estimación de lo que está hecho y lo que falta para completar este entregable?

**Comment by spitxa** [comment]
actualizado en el github de izertis y cerrado.
