### ISSUE TITLE
🚩 Análisis y Métodos FAIR

### ISSUE THREAD

**Issue by thewillyhuman** [weso/hercules-ontology#89]
El día 15 de mayo de 2020 se realiza la entrega del hito 1 para el proyecto hércules. Este issue representa el entregable **_Análisis y métodos FAIR_** del cual el tipo de entregable es: **_Documento_**.

>**Nota:** Si no me equivoco este entregable lo está realizando el equipo de la arquitectura semántica.

**Comment by thewillyhuman** [comment]
@labra podrías confirmar si este entregable lo están haciendo los compañeros de A.S.?

**Comment by alejgh** [comment]
Sí, en principio todo esto se encuentra documentado ya. Procedo a cerrar el issue. En caso de que haya cualquier duda o noticia lo podemos reabrir sin problema.

**Comment by thewillyhuman** [comment]
Always nice to have a reply!
