### ISSUE TITLE
CQ001 - Obtain list of research centers based on discipline

### ISSUE THREAD

**Issue by alejgh** [weso/hercules-ontology#9]
Original source:
> Como usuario requiero obtener un listado de los centros/estructuras de investigación que trabajan en un área/disciplina específica.
<br>

Translated:
> As a user I want to obtain a list of research centres/structures which work in a specific area/discipline.

**Comment by spitxa** [comment]
-created new property ('has research line') linking organizations with scientific domain
<img width="1023" alt="Captura de Pantalla 2020-04-22 a les 16 13 50" src="https://user-images.githubusercontent.com/28587554/79992920-6dd6e100-84b4-11ea-8173-4dca829ad3f4.png">

**Comment by alejgh** [comment]
Nice, we can start working now on this CQ and many others which are related. :)

**Comment by alejgh** [comment]
Closed in #113
